output_path: path\to\outputs
# a subfolder with mode and zone name will be created within the output path

mode: car
# Options: foot | car | bike

route_by: distance
# Options: distance | time
# Note: time is currently only supported for car mode.

zones:
  name: name_zones
  path: path\to\zones.shp
  id_col: zone_id
  zone_name_col: zone_name
  zone_system_col: zone_system
  internal_zone_system: OA

centroids:
  name: oa_centroids
  path: path\to\centroids.shp
  id_col: OA21CD

# PostGIS database connection parameters
database:
  username: username
  password: password
  host: localhost
  database: postgis
  port: 5432